name: my_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  flutter_markdown: ^0.6.15
  flutter_tts: ^3.6.3
  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.5.3
  model_viewer_plus: ^1.9.3 # 添加 model_viewer_plus 插件

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/black_rat__free_download.glb # 添加 3D 模型文件路径